# Generated by Django 4.1.5 on 2023-01-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0003_alter_category_slug_alter_subcategory_slug_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name_plural': '3. Ranks'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '2. Sub categories'},
        ),
        migrations.RemoveField(
            model_name='rank',
            name='sub_category_id',
        ),
    ]
