# Generated by Django 4.1.5 on 2023-01-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0004_alter_category_options_alter_rank_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='rank',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
