# Generated by Django 4.1.5 on 2023-01-24 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0005_alter_category_slug_alter_rank_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('about_me', models.TextField()),
                ('pendidikan', models.TextField()),
                ('pengalaman_kerja', models.TextField()),
                ('keahlian', models.TextField()),
                ('pengalaman', models.TextField()),
                ('sosmed', models.CharField(choices=[('fb', 'Facebook'), ('tw', 'Twitter'), ('link', 'Linktend'), ('ig', 'Insta Gram')], default='fb', max_length=5)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='sekdilu139.category')),
                ('jabatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekdilu139.rank')),
            ],
            options={
                'ordering': ['-publish'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-publish'], name='sekdilu139__publish_7747e8_idx'),
        ),
    ]
