# Generated by Django 4.1.5 on 2023-01-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekdilu139', '0006_person_person_sekdilu139__publish_7747e8_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to='media/person/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(help_text='This field will be automatically added.', max_length=250, unique=True),
        ),
    ]
